### ISSUE TITLE
Dependency Not Installed

### ISSUE THREAD

**Issue by abrad1212** [tambetm/gym-minecraft#13]
I keep getting an error saying
`DependencyNotInstalled: No module named 'minecraft_py'. (HINT: install minecraft_py from https://github.com/tambetm/minecraft-py`

When I definitely do have `minecraft-py` installed.

**Comment by tambetm** [comment]
I'm sorry this took so long to respond. Probably installation of minecraft_py failed to compile MalmoPython extension, the error handling could be improved. What operating system you are using? Under Ubuntu you could use one of the precompiled versions: [for 14.04](https://github.com/tambetm/minecraft-py34-ubuntu1404) or [for 16.04](https://github.com/tambetm/minecraft-py35-ubuntu1604).
