### ISSUE TITLE
Is it possible to use my own XML environment?

### ISSUE THREAD

**Issue by JunhongXu** [tambetm/gym-minecraft#14]
The environments provided in gym include several tasks defined in Project Malmo. It should be more interesting if we can add our own environments.

**Comment by tambetm** [comment]
Sure, hidden under the hood are two environment methods: `env.load_mission_file(file_path)` and `env.load_mission_xml(xml)`. There is very basic documentation here:
https://github.com/tambetm/gym-minecraft/wiki/Configure#additional-methods
