### ISSUE TITLE
Does client_pool work?

### ISSUE THREAD

**Issue by SuperLinguini** [tambetm/gym-minecraft#16]
I keep getting this error when running `env.init(client_pool=[('127.0.0.1', 10001)])`. I've launched the Malmo server using `./launchClient -port 10001`.
Error:
`Error starting mission: Failed to find an available client for this mission - tried all the clients in the supplied client pool.`

**Comment by tambetm** [comment]
The last time I tested it worked, but it has been a while. Does `telnet 127.0.0.1 10001` connect?

**Comment by SuperLinguini** [comment]
While Minecraft is running I get,
`Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.`
When it's not I get,
`Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused`

**Comment by tambetm** [comment]
Does it work with port 10000, which is the default? I.e. if you don't pass `-port 10001` to `./launchClient.sh` and don't pass `client_pool` to `env.init()`?

**Comment by SuperLinguini** [comment]
Nevermind. It just wasn't working on my Ubuntu dual boot.
