### ISSUE TITLE
In there any enemy present in MinecraftBasic-v0 ??

### ISSUE THREAD

**Issue by adil25** [tambetm/gym-minecraft#23]
Fist of all, excuse me for asking a question in the shape of an issue, 
In MinecraftBasic-v0 the agent needs to touch the target block in partially observable environment where there is no lava. My question is that is there any enemy in that grey room where the agent need to touch the target block. Please how can i find a detail information about MinecraftBasic-v0 such as enemy, food, Air, life, Damage taken, Damage Dealt etc etc etc.
I will be thankful if someone replies with a little detail to my question.

**Comment by tambetm** [comment]
MinecraftBasic-v0 contains no enemies. All Malmö missions are described using XML files, see the [file for MinecraftBasic-v0](https://github.com/tambetm/gym-minecraft/blob/master/gym_minecraft/assets/basic.xml). In particular this mission uses [ClassroomDecorator](http://microsoft.github.io/malmo/0.30.0/Schemas/MissionHandlers.html#element_ClassroomDecorator) to generate rooms. If you want more control over the world contents, [DrawingDecorator](http://microsoft.github.io/malmo/0.30.0/Schemas/MissionHandlers.html#element_DrawingDecorator) allows you to produce any world you want, including placing enemies. The links above are to XML schema documentation. While it can be confusing and hard to read, I'm not aware of any better documentation. [Example missions](https://github.com/Microsoft/malmo/tree/master/sample_missions) distributed with Malmö are also good source of hints.

**Comment by adil25** [comment]
@tambetm ok, Thanks
