### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by Nicolas99-9** [tambetm/gym-minecraft#8]
Hi ! 
I have a problem with the installation (step 5).
I have tried to run the code but there is path problem : 

```
>>> import minecraft_py
>>> proc, port = minecraft_py.start()
INFO:minecraft_py:Starting Minecraft process: /home/nicolas/miniconda2/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/launchClient.sh -port 10000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nicolas/miniconda2/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/__init__.py", line 64, in start
    preexec_fn=os.setsid)
  File "/home/nicolas/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/nicolas/miniconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/home/nicolas/miniconda2/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft
```

I checked the path  (/miniconda2/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py).
It only contains two files : 
__init__.py
__init__.pyc

Yet I followed all the installation steps

**Comment by tambetm** [comment]
Can you post output of the `python setup.py install` command for minecraft-py? Also you could try `python setup.py develop`, which should get around the writable directory issue. Probably should include it in README.

**Comment by Nicolas99-9** [comment]
I fixed the problem by using the pre-compiled version of Malmo.
There is still a problem, when I launch the game 2 windows are opened. One named "pygame" and the other one named "minecraft".

**Comment by scientist1642** [comment]
Hi Tambet, 
I also have this problem `setup.py` generates this url for MAC, which doesn't exist:
https://github.com/Microsoft/malmo/releases/download/0.18.0/Malmo-0.18.0-Darwin-64bit.zip

**Comment by tambetm** [comment]
@Nicolas99-9 two windows are expected. There is always "minecraft" window and the "pygame" window appears when you call `render()`. If you run docker image, then you can also get rid of "minecraft" window.

@scientist1642 MacOS error should now be fixed with https://github.com/tambetm/minecraft-py/pull/2.
