### ISSUE TITLE
Reset performance

### ISSUE THREAD

**Issue by Nicolas99-9** [tambetm/gym-minecraft#9]
I have a problem with reset, I'm using the eating_1.xml mission.
Each time I reset the environment my inventory is cleared but the items (the food) are not erased so after a few iteration the map is fulled by thousands of fruits. I could use forceWorldReset() but it's very slow. How to fully reset the map or avoid the spawning of already present fruits

**Comment by tambetm** [comment]
I think forceWorldReset is your only option. There is `init()` parameter for this, see [Configure](https://github.com/tambetm/gym-minecraft/wiki/Configure#other).
